stages:
- name: Build and push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sandbox-image:${CICD_EXECUTION_SEQUENCE}
- name: Deploy react app workloads
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
notification:
  recipients:
  - recipient: '#rancher'
    notifier: c-bs26q:n-swhzd
  condition:
  - Success
  - Changed
  - Failed
