kind: Service
apiVersion: v1
metadata:
  name: sandbox-app-service
spec:
  selector:
    app: sandbox-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-app-server
  labels:
    app: sandbox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-app
  template:
    metadata:
      labels:
        app: sandbox-app
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: sandbox-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3000