kind: Service
apiVersion: v1
metadata:
  name: sandbox-app-balancer
spec:
  selector:
    app: sandbox-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-app-server
  labels:
    app: sandbox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-app
  template:
    metadata:
      labels:
        app: sandbox-app
    spec:
      imagePullSecrets:
      - name: petrovmp89
      containers:
      - name: sandbox-app
        image: petrovmp89/sandbox-image:latest
        ports:
        - containerPort: 3000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sandbox-app-ingress
spec:
  rules:
  - host: sandbox-app.garantme.fr
    http:
      paths:
      - backend:
          serviceName: sandbox-app-balancer
          servicePort: 3000
        path: /
        pathType: Prefix
